server:
  port: ${serverPort:443}
  contextPath: ${serverContextPath:/}
  use-forward-headers: true
  ssl:
    key-store: ${keystoreLocation}
    key-store-password: ${keystorePassword}
    key-password: ${keystorePassword}
    key-alias: ${keystoreSSLKey:tomcat}

zuul:
  retryable: true
  ribbonIsolationStrategy: SEMAPHORE
  routes:
   computationsLookup:
      path: /service/lookup/computations/**
      serviceId: aqcu/aqcu-webservice/service/lookup/computations
      stripPrefix: true
   controlConditionsLookup:
      path: /service/lookup/controlConditions/**
      serviceId: aqcu/aqcu-webservice/service/lookup/controlConditions
      stripPrefix: true
   derivationChainFindLookup:
      path: /service/lookup/derivationChain/find/**
      serviceId: aqcu/aqcu-webservice/service/lookup/derivationChain/find
      stripPrefix: true
   derivationChainRatingModelLookup:
      path: /service/lookup/derivationChain/ratingModel/**
      serviceId: aqcu/aqcu-webservice/service/lookup/derivationChain/ratingModel
      stripPrefix: true
   fieldVisitDatesLookup:
      path: /service/lookup/field-visit-dates/**
      serviceId: aqcu/aqcu-webservice/service/lookup/field-visit-dates
      stripPrefix: true
   periodsLookup:
      path: /service/lookup/periods/**
      serviceId: aqcu/aqcu-webservice/service/lookup/periods
      stripPrefix: true
   reportTypesLookup:
      path: /service/lookup/report/types/**
      serviceId: aqcu/aqcu-webservice/service/lookup/report/types
      stripPrefix: true
   sitefileLookup:
      path: /service/lookup/sitefile/**
      serviceId: aqcu/aqcu-webservice/service/lookup/sitefile
      stripPrefix: true
   sitesLookup:
      path: /service/lookup/sites/**
      serviceId: aqcu/aqcu-webservice/service/lookup/sites
      stripPrefix: true
   timeseriesProcessorTypesLookup:
      path: /service/lookup/timeseries/processorTypes/**
      serviceId: aqcu/aqcu-webservice/service/lookup/timeseries/processorTypes
      stripPrefix: true
   timeseriesIdentifiersLookup:
      path: /service/lookup/timeseries/identifiers/**
      serviceId: aqcu/aqcu-webservice/service/lookup/timeseries/identifiers
      stripPrefix: true
   unitsLookup:
      path: /service/lookup/units/**
      serviceId: aqcu/aqcu-webservice/service/lookup/units
      stripPrefix: true

   correctionsataglanceReport:
      path: /service/reports/correctionsataglance/**
      serviceId: aqcu/aqcu-webservice/service/reports/correctionsataglance
      stripPrefix: true
   derivationchainReport:
      path: /service/reports/derivationchain/**
      serviceId: aqcu/aqcu-webservice/service/reports/derivationchain
      stripPrefix: true
   dvhydrographReport:
      path: /service/reports/dvhydrograph/**
      serviceId: aqcu/aqcu-webservice/service/reports/dvhydrograph
      stripPrefix: true
   exampleReport:
      path: /service/reports/example/**
      serviceId: aqcu/aqcu-webservice/service/reports/example
      stripPrefix: true
   extremesReport:
      path: /service/reports/extremes/**
      serviceId: aqcu/aqcu-webservice/service/reports/extremes
      stripPrefix: true
   fiveyeargwsumReport:
      path: /service/reports/fiveyeargwsum/**
      serviceId: aqcu/aqcu-webservice/service/reports/fiveyeargwsum
      stripPrefix: true
   flattenXformExampleReport:
      path: /service/reports/flattenXformExample/**
      serviceId: aqcu/aqcu-webservice/service/reports/flattenXformExample
      stripPrefix: true
   ratingReport:
      path: /service/reports/rating/**
      serviceId: aqcu/aqcu-webservice/service/reports/rating
      stripPrefix: true
   sensorreadingsummaryReport:
      path: /service/reports/sensorreadingsummary/**
      serviceId: aqcu/aqcu-webservice/service/reports/sensorreadingsummary
      stripPrefix: true
   sitevisitpeakReport:
      path: /service/reports/sitevisitpeak/**
      serviceId: aqcu/aqcu-webservice/service/reports/sitevisitpeak
      stripPrefix: true
   timeseriessummaryReport:
      path: /service/reports/timeseriessummary/**
      serviceId: aqcu/aqcu-webservice/service/reports/timeseriessummary
      stripPrefix: true
   uvhydrographReport:
      path: /service/reports/uvhydrograph/**
      serviceId: aqcu/aqcu-webservice/service/reports/uvhydrograph
      stripPrefix: true
   vdiagramReport:
      path: /service/reports/vdiagram/**
      serviceId: aqcu/aqcu-webservice/service/reports/vdiagram
      stripPrefix: true
   xformExampleReport:
      path: /service/reports/xformExample/**
      serviceId: aqcu/aqcu-webservice/service/reports/xformExample
      stripPrefix: true

   health:
      path: /service/health/**
      serviceId: aqcu/aqcu-webservice/service/health
      stripPrefix: true

   echo:
      path: /service/echo/**
      serviceId: aqcu/aqcu-webservice/service/echo
      stripPrefix: true

   batch:
      path: /service/batch/**
      serviceId: aqcu/aqcu-webservice/service/batch
      stripPrefix: true


#Legacy Services

aqcu/aqcu-webservice/service/lookup/computations:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu/aqcu-webservice/service/lookup/controlConditions:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu/aqcu-webservice/service/lookup/derivationChain/find:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu/aqcu-webservice/service/lookup/derivationChain/ratingModel:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu/aqcu-webservice/service/lookup/field-visit-dates:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu/aqcu-webservice/service/lookup/periods:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu/aqcu-webservice/service/lookup/report/types:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu/aqcu-webservice/service/lookup/sitefile:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu/aqcu-webservice/service/lookup/sites:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu/aqcu-webservice/service/lookup/timeseries/processorTypes:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu/aqcu-webservice/service/lookup/timeseries/identifiers:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu/aqcu-webservice/service/lookup/units:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu/aqcu-webservice/service/reports/correctionsataglance:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu/aqcu-webservice/service/reports/derivationchain:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu/aqcu-webservice/service/reports/dvhydrograph:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu/aqcu-webservice/service/reports/example:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu/aqcu-webservice/service/reports/extremes:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu/aqcu-webservice/service/reports/fiveyeargwsum:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu/aqcu-webservice/service/reports/flattenXformExample:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu/aqcu-webservice/service/reports/rating:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu/aqcu-webservice/service/reports/sensorreadingsummary:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu/aqcu-webservice/service/reports/sitevisitpeak:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu/aqcu-webservice/service/reports/timeseriessummary:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu/aqcu-webservice/service/reports/uvhydrograph:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 10000000

aqcu/aqcu-webservice/service/reports/vdiagram:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu/aqcu-webservice/service/reports/xformExample:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu/aqcu-webservice/service/health:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu/aqcu-webservice/service/echo:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu/aqcu-webservice/service/batch:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

# New Services

aqcu/dvhydrograph:
  ribbon:
    listOfServers: ${dvhydroReportServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu/timeseriessummary:
  ribbon:
    listOfServers: ${tssReportServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000


eureka:
  client:
    enabled: false

feign:
  hystrix:
    enabled: true

ribbon:
  MaxAutoRetries: ${ribbonMaxAutoRetries}
  MaxAutoRetriesNextServer: 0
  ConnectTimeout: ${ribbonConnectTimeout}
  ReadTimeout: ${ribbonReadTimeout}
  OkToRetryOnAllOperations: true

hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: ${hystrixThreadTimeout}

security:
  require-ssl: true
  basic:
    enabled: false

management:
  security:
    enabled: false

spring:
  profiles:
    active: default, swagger
  application:
    name: aqcu-gateway
  jmx:
    default-domain: aqcu-gateway
