server:
  port: ${serverPort:443}
  use-forward-headers: true
  ssl:
    key-store: ${keystoreLocation}
    key-store-password: ${keystorePassword}
    key-password: ${keystorePassword}
    key-alias: ${keystoreSSLKey:tomcat}

zuul:
  retryable: true
  ribbonIsolationStrategy: SEMAPHORE
  routes:
    legacyComputationsLookup:
      path: /service/lookup/computations
      serviceId: aqcu-webservice/service/lookup/computations
      stripPrefix: false
    legacyControlConditionsLookup:
      path: /service/lookup/controlConditions
      serviceId: aqcu-webservice/service/lookup/controlConditions
      stripPrefix: false
    legacyDerivationChainFindLookup:
      path: /service/lookup/derivationChain/find
      serviceId: aqcu-webservice/service/lookup/derivationChain/find
      stripPrefix: false
    legacyDerivationChainRatingModelLookup:
      path: /service/lookup/derivationChain/ratingModel
      serviceId: aqcu-webservice/service/lookup/derivationChain/ratingModel
      stripPrefix: false
    legacyFieldVisitDatesLookup:
      path: /service/lookup/field-visit-dates
      serviceId: aqcu-webservice/service/lookup/field-visit-dates
      stripPrefix: false
    legacyPeriodsLookup:
      path: /service/lookup/periods
      serviceId: aqcu-webservice/service/lookup/periods
      stripPrefix: false
    legacyReportTypesLookup:
      path: /service/lookup/report/types
      serviceId: aqcu-webservice/service/lookup/report/types
      stripPrefix: false
    legacySitefileLookup:
      path: /service/lookup/sitefile
      serviceId: aqcu-webservice/service/lookup/sitefile
      stripPrefix: false
    legacySitesLookup:
      path: /service/lookup/sites
      serviceId: aqcu-webservice/service/lookup/sites
      stripPrefix: false
    legacyTimeseriesProcessorTypesLookup:
      path: /service/lookup/timeseries/processorTypes
      serviceId: aqcu-webservice/service/lookup/timeseries/processorTypes
      stripPrefix: false
    legacyTimeseriesIdentifiersLookup:
      path: /service/lookup/timeseries/identifiers
      serviceId: aqcu-webservice/service/lookup/timeseries/identifiers
      stripPrefix: false
    legacyUnitsLookup:
      path: /service/lookup/units
      serviceId: aqcu-webservice/service/lookup/units
      stripPrefix: false

    legacyCorrectionsataglanceReport:
      path: /service/reports/correctionsataglance/**
      serviceId: aqcu-webservice/service/reports/correctionsataglance
      stripPrefix: false
    legacyDerivationchainReport:
      path: /service/reports/derivationchain/**
      serviceId: aqcu-webservice/service/reports/derivationchain
      stripPrefix: false
    legacyDvhydrographReport:
      path: /service/reports/dvhydrograph/**
      serviceId: aqcu-webservice/service/reports/dvhydrograph
      stripPrefix: false
    legacyExampleReport:
      path: /service/reports/example/**
      serviceId: aqcu-webservice/service/reports/example
      stripPrefix: false
    legacyExtremesReport:
      path: /service/reports/extremes/**
      serviceId: aqcu-webservice/service/reports/extremes
      stripPrefix: false
    legacyFiveyeargwsumReport:
      path: /service/reports/fiveyeargwsum/**
      serviceId: aqcu-webservice/service/reports/fiveyeargwsum
      stripPrefix: false
    legacyFlattenXformExampleReport:
      path: /service/reports/flattenXformExample/**
      serviceId: aqcu-webservice/service/reports/flattenXformExample
      stripPrefix: false
    legacyRatingReport:
      path: /service/reports/rating
      serviceId: aqcu-webservice/service/reports/rating
      stripPrefix: false
    legacySensorreadingsummaryReport:
      path: /service/reports/sensorreadingsummary/**
      serviceId: aqcu-webservice/service/reports/sensorreadingsummary
      stripPrefix: false
    legacySitevisitpeakReport:
      path: /service/reports/sitevisitpeak/**
      serviceId: aqcu-webservice/service/reports/sitevisitpeak
      stripPrefix: false
    legacyTimeseriessummaryReport:
      path: /service/reports/timeseriessummary/**
      serviceId: aqcu-webservice/service/reports/timeseriessummary
      stripPrefix: false
    legacyUvhydrographReport:
      path: /service/reports/uvhydrograph/**
      serviceId: aqcu-webservice/service/reports/uvhydrograph
      stripPrefix: false
    legacyVdiagramReport:
      path: /service/reports/vdiagram/**
      serviceId: aqcu-webservice/service/reports/vdiagram
      stripPrefix: false
    legacyXformExampleReport:
      path: /service/reports/xformExample/**
      serviceId: aqcu-webservice/service/reports/xformExample
      stripPrefix: false

    legacyHealth:
      path: /service/health/**
      serviceId: aqcu-webservice/service/health/**
      stripPrefix: false

    legacyEcho:
      path: /service/echo/**
      serviceId: aqcu-webservice/service/echo/**
      stripPrefix: false

    legacyBatch:
      path: /service/batch/**
      serviceId: aqcu-webservice/service/batch/**
      stripPrefix: false


aqcu-webservice/service/lookup/computations:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu-webservice/service/lookup/controlConditions:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu-webservice/service/lookup/derivationChain/find:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu-webservice/service/lookup/derivationChain/ratingModel:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu-webservice/service/lookup/field-visit-dates:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu-webservice/service/lookup/periods:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu-webservice/service/lookup/report/types:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu-webservice/service/lookup/sitefile:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu-webservice/service/lookup/sites:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu-webservice/service/lookup/timeseries/processorTypes:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu-webservice/service/lookup/timeseries/identifiers:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu-webservice/service/lookup/units:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyLookupIsSecure:true}

aqcu-webservice/service/reports/correctionsataglance:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu-webservice/service/reports/derivationchain:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu-webservice/service/reports/dvhydrograph:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu-webservice/service/reports/example:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu-webservice/service/reports/extremes:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu-webservice/service/reports/fiveyeargwsum:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu-webservice/service/reports/flattenXformExample:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu-webservice/service/reports/rating:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu-webservice/service/reports/sensorreadingsummary:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu-webservice/service/reports/sitevisitpeak:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu-webservice/service/reports/timeseriessummary:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu-webservice/service/reports/uvhydrograph:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 10000000

aqcu-webservice/service/reports/vdiagram:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu-webservice/service/reports/xformExample:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu-webservice/service/health/**:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu-webservice/service/echo/**:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

aqcu-webservice/service/batch/**:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}
    ReadTimeout: 100000

eureka:
  client:
    enabled: false

feign:
  hystrix:
    enabled: true

ribbon:
  MaxAutoRetries: ${ribbonMaxAutoRetries}
  MaxAutoRetriesNextServer: 0
  ConnectTimeout: ${ribbonConnectTimeout}
  ReadTimeout: ${ribbonReadTimeout}
  OkToRetryOnAllOperations: true

hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: ${hystrixThreadTimeout}

security:
  require-ssl: true
  basic:
    enabled: false

management:
  security:
    enabled: false

spring:
  profiles:
    active: default, swagger
  application:
    name: aqcu-gateway
  jmx:
    default-domain: aqcu-gateway
