server:
  port: ${serverPort:8443}
  servlet:
    context-path: ${serverContextPath:/}
  use-forward-headers: true
  ssl:
    key-store: ${keystoreLocation}
    key-store-password: ${keystorePassword}
    key-password: ${keystorePassword}
    key-alias: ${keystoreSSLKey:tomcat}
    enabled-protocols: TLSv1.2
  max-http-header-size: 16KB

zuul:
  retryable: true
  sensitiveHeaders: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  ignoredHeaders: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  ribbonIsolationStrategy: SEMAPHORE
  routes:
    # Lookups
    allLookups:
      path: /service/lookup/**
      serviceId: aqcu/lookup
      stripPrefix: true
    allConifgs:
      path: /service/config/**
      serviceId: aqcu/config
      stripPrefix: true
    # Reports
    correctionsataglanceReport:
      path: /service/reports/correctionsataglance/**
      serviceId: aqcu/correctionsataglance
      stripPrefix: true
    derivationchainReport:
      path: /service/reports/derivationchain/**
      serviceId: aqcu/derivationchain
      stripPrefix: true
    dvhydrographReport:
      path: /service/reports/dvhydrograph/**
      serviceId: aqcu/dvhydro
      stripPrefix: true
    extremesReport:
      path: /service/reports/extremes/**
      serviceId: aqcu/extremes
      stripPrefix: true
    fiveyeargwsumReport:
      path: /service/reports/fiveyeargwsum/**
      serviceId: aqcu/fiveyeargwsum
      stripPrefix: true
    sensorreadingsummaryReport:
      path: /service/reports/sensorreadingsummary/**
      serviceId: aqcu/sensorreadingsummary
      stripPrefix: true
    sitevisitpeakReport:
      path: /service/reports/sitevisitpeak/**
      serviceId: aqcu/sitevisitpeak
      stripPrefix: true
    timeseriessummaryReport:
      path: /service/reports/timeseriessummary/**
      serviceId: aqcu/timeseriessummary
      stripPrefix: true
    uvhydrographReport:
      path: /service/reports/uvhydrograph/**
      serviceId: aqcu/uvhydrograph
      stripPrefix: true
    vdiagramReport:
      path: /service/reports/vdiagram/**
      serviceId: aqcu/vdiagram
      stripPrefix: true
    # Other
    health:
      path: /service/health/**
      serviceId: aqcu/aqcu-webservice/service/health
      stripPrefix: true
    echo:
      path: /service/echo/**
      serviceId: aqcu/aqcu-webservice/service/echo
      stripPrefix: true
    batch:
      path: /service/batch/**
      serviceId: aqcu/aqcu-webservice/service/batch
      stripPrefix: true

#Legacy Services
aqcu/aqcu-webservice/service/health:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}

aqcu/aqcu-webservice/service/echo:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}

aqcu/aqcu-webservice/service/batch:
  ribbon:
    listOfServers: ${legacyServerList}
    IsSecure: ${legacyIsSecure:true}

# New Services
aqcu/correctionsataglance:
  ribbon:
    listOfServers: ${corrReportServerList}
    IsSecure: ${corrReportIsSecure:true}

aqcu/derivationchain:
  ribbon:
    listOfServers: ${dcReportServerList}
    IsSecure: ${dcReportIsSecure:true}

aqcu/dvhydro:
  ribbon:
    listOfServers: ${dvhydroReportServerList}
    IsSecure: ${dvhydroReportIsSecure:true}

aqcu/extremes:
  ribbon:
    listOfServers: ${extReportServerList}
    IsSecure: ${extReportIsSecure:true}

aqcu/fiveyeargwsum:
  ribbon:
    listOfServers: ${fiveYearReportServerList}
    IsSecure: ${fiveYearReportIsSecure:true}

aqcu/sensorreadingsummary:
  ribbon:
    listOfServers: ${srsReportServerList}
    IsSecure: ${srsReportIsSecure:true}

aqcu/sitevisitpeak:
  ribbon:
    listOfServers: ${svpReportServerList}
    IsSecure: ${svpReportIsSecure:true}
    
aqcu/timeseriessummary:
  ribbon:
    listOfServers: ${tssReportServerList}
    IsSecure: ${tssReportIsSecure:true}

aqcu/uvhydrograph:
  ribbon:
    listOfServers: ${uvhydroReportServerList}
    IsSecure: ${uvhydroReportIsSecure:true}

aqcu/vdiagram:
  ribbon:
    listOfServers: ${vdiReportServerList}
    IsSecure: ${vdiReportIsSecure:true}

aqcu/lookup:
  ribbon:
    listOfServers: ${lookupServiceServerList}
    IsSecure: ${lookupServiceIsSecure:true}

aqcu/config:
  ribbon:
    listOfServers: ${lookupServiceServerList}
    IsSecure: ${lookupServiceIsSecure:true}

lambda:
  region: "us-west-2"
  functions:
    gwvisitreviewstatus: 
      name: "GWVRStatReportFunction"
      timeout: 180000
    gwvisitextremes: 
      name: "GWVExtReportFunction"
      timeout: 180000

eureka:
  client:
    enabled: false

ribbon:
  MaxAutoRetries: ${ribbonMaxAutoRetries}
  MaxAutoRetriesNextServer: 0
  ConnectTimeout: ${ribbonConnectTimeout}
  ReadTimeout: ${ribbonReadTimeout}
  OkToRetryOnAllOperations: true

aqcu:
  login:
    url: ${aqcuLoginUrl:https://localhost:443/}
  ui:
    login:
      route: https://localhost:7000/login 

security:
  require-ssl: true
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ${oauthClientId}
      clientSecret: ${oauthClientSecret}
      accessTokenUri: ${oauthClientAccessTokenUri}
      userAuthorizationUri: ${oauthClientAuthorizationUri}
    resource:
      id: ${oauthResourceId}
      jwt:
        keyUri: ${oauthResourceTokenKeyUri}

management:
  security:
    enabled: false

spring:
  profiles:
    active: default
  application:
    name: aqcu-gateway
  jmx:
    default-domain: aqcu-gateway
